package com.example.demo.entity;
// Generated Jun 1, 2018 1:13:31 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AppRole generated by hbm2java
 */
@Entity
@Table(name = "app_role", catalog = "jpalogindb", uniqueConstraints = @UniqueConstraint(columnNames = "ROLE_NAME"))
public class AppRole {

	private long roleId;
	private String roleName;
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);

	public AppRole() {
	}

	public AppRole(long roleId, String roleName) {
		this.roleId = roleId;
		this.roleName = roleName;
	}

	public AppRole(long roleId, String roleName, Set<UserRole> userRoles) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.userRoles = userRoles;
	}

	@Id

	@Column(name = "ROLE_ID", unique = true, nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "ROLE_NAME", unique = true, nullable = false, length = 30)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}


}
